# Generated by Django 3.0.3 on 2020-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('LastSync', models.DateTimeField()),
                ('LastMessageAccepted', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='IO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Input'), ('O', 'Output'), ('JR', 'I2C_TMP102')], max_length=2)),
                ('stateInteger', models.IntegerField(default=0)),
                ('stateText', models.CharField(max_length=32)),
                ('stateDecimal', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
