# Generated by Django 3.0.4 on 2020-03-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_io_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='LastMessageAccepted',
            new_name='lastMessageAccepted',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='LastSync',
            new_name='lastSync',
        ),
    ]
